CREATE TABLE Person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       username varchar(100) NOT NULL,
                       password varchar NOT NULL,
                       role varchar(100) NOT NULL
);

INSERT INTO Person (username, "password", role) VALUES ('test_user1', 'test_password', 'ROLE_EMPL');


CREATE TABLE GitRepositories(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar(30) NOT NULL,
                       text_programm varchar,
                       command varchar(20) NOT NULL
);

CREATE TABLE CICDDeployment(
                                id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                status varchar NOT NULL,
                                platform varchar(30) NOT NULL,
                                command varchar(20) NOT NULL
);